setup-root: Put the user/group databases early in rootfs setup
flatcar-linux/bootengine pull request #18
Opened 2020-09-30 18:06 UTC by krnowak

This PR is a part of the systemd update.

systemd-tmpfiles in systemd v246 requires the user and group databases
in the custom root if it's invoked with --root flag. This change
prepares for it.

Test build is here: http://localhost:9091/job/os/job/manifest/1138/

2020-10-01 10:38 UTC, pothos approved these changes
Thanks, looks good in general. The cl.ignition.v*.*root tests seem to be broken by another cause.

2020-10-01 10:47 UTC, pothos requested changes
see https://github.com/flatcar-linux/baselayout/pull/6#pullrequestreview-500224220

2020-10-05 11:49 UTC, krnowak commented
Test are fine now - kola qemu passed. See http://localhost:9091/job/os/job/manifest/1154/cldsv/

2020-10-06 15:36 UTC, dongsupark approved these changes
Looks good, if CI passed.

2020-10-08 16:38 UTC, merged